### ISSUE TITLE
[2.0.0B1] Invalid algo after applying template

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#262] opened 2019-08-29 16:59 UTC
After applying template with different algo than current, miners show 'invalid' algo in CC server dashboard but mine with apparently previous algo and pool, at least hashrate matches previous algo but there's no log entries about pool & jobs. Explicitly restarting miner through CC server fixes the problem.

Log:

[2019-08-29 21:44:26.583] [CC-Client] Command: UPDATE_CONFIG received -> update config
[2019-08-29 21:44:26.657] [CC-Client] Config updated. -> reload
[2019-08-29 21:44:27.157] "config.json" was changed, reloading configuration
 * POOL #1      iridium.herominers.com:10640 algo cn-pico
[2019-08-29 21:44:36.662] speed 10s/60s/15m n/a n/a 6303.9 H/s max 6874.6 H/s
[2019-08-29 21:44:37.254] resumed
[2019-08-29 21:45:36.921] speed 10s/60s/15m 6454.4 6398.2 3568.7 H/s max 6874.6 H/s
[2019-08-29 21:46:37.408] speed 10s/60s/15m 6316.3 6368.6 3572.4 H/s max 6874.6 H/s
[2019-08-29 21:47:37.840] speed 10s/60s/15m 6406.7 6417.6 3581.2 H/s max 6874.6 H/s

**Comment by Bendr0id** [comment] 2019-08-29 17:04
Please provide the templates. For me this works just fine, only on the case when the cpu config/disabled algos change it needs to wait for the next job which can take some time but heals itself. Doing a restart after applying a new config may be a good solution..

**Comment by uz-spark** [comment] 2019-08-29 17:14
Template A (previous) : https://pastebin.com/65sgx0hL
Template B (new) : https://pastebin.com/mMKtGZum

That's strange, when i tried doing it in reverse, miners (tried on two) disappear from dashboard while miners log shows this :

[2019-08-29 22:11:56.217] [CC-Client] Command: UPDATE_CONFIG received -> update config
[2019-08-29 22:11:56.277] [CC-Client] Config updated. -> reload
[2019-08-29 22:11:56.778] "x\config.json" was changed, reloading configuration
POOL #1      uplexa.herominers.com:10470 algo cn-extremelite/upx2
[2019-08-29 22:12:06.899] paused, press  r  to resume
[2019-08-29 22:12:16.973] speed 10s/60s/15m n/a n/a n/a H/s max 15571.0 H/s
[2019-08-29 22:13:17.441] speed 10s/60s/15m n/a n/a n/a H/s max 15571.0 H/s

**Comment by uz-spark** [comment] 2019-08-29 17:16
Hitting 'r' - resume, doesn't work. Restarting miner still works (not through dashboard since it doesn't show there).

**Comment by Bendr0id** [comment] 2019-08-29 17:34
Hmm i can't reproduce it..

```
[2019-08-29 19:29:11.911] use pool iridium.herominers.com:10640  78.46.106.203
[2019-08-29 19:29:11.911] new job from iridium.herominers.com:10640 diff 50000 algo cn-pico
[2019-08-29 19:29:11.911]  cpu  use profile  cn-pico  (4 threads) scratchpad 256 KB
[2019-08-29 19:29:12.001]  cpu  READY threads 4(8) huge pages 4/4 100% memory 2048 KB (16 ms)
[2019-08-29 19:29:13.478] accepted (1618/0) diff 50000 (24 ms)
[2019-08-29 19:29:15.795] accepted (1619/0) diff 50000 (27 ms)
[2019-08-29 19:29:20.195] new job from iridium.herominers.com:10640 diff 100001 algo cn-pico
[2019-08-29 19:29:27.530] accepted (1620/0) diff 100001 (38 ms)
[2019-08-29 19:29:31.319] speed 10s/60s/15m 3757.6 n/a n/a H/s max 3758.9 H/s
[2019-08-29 19:29:51.886] [CC-Client] Command: UPDATE_CONFIG received -> update config
[2019-08-29 19:29:52.434] [CC-Client] Config updated. -> reload
[2019-08-29 19:29:52.934] "/home/vidi/bin/xmrigCC/config.json" was changed, reloading configuration
 * POOL #1      donate.graef.in:4000 algo auto
[2019-08-29 19:29:53.467] use pool donate.graef.in:4000 TLSv1.2 3.123.78.48
[2019-08-29 19:29:53.467] fingerprint (SHA-256): "ea889afbe39786167b3d1eba2ff1f09ebc73e9be28b52ff246e9d16912b735bc"
[2019-08-29 19:29:53.467] new job from donate.graef.in:4000 diff 10000 algo cn/r height 1911568
[2019-08-29 19:29:53.467]  cpu  use profile  cn  (4 threads) scratchpad 2048 KB
[2019-08-29 19:29:54.070]  cpu  READY threads 4(4) huge pages 4/4 100% memory 8192 KB (601 ms)
[2019-08-29 19:30:09.135] new job from donate.graef.in:4000 diff 10000 algo cn/r height 1911569
[2019-08-29 19:30:11.714] accepted (1621/0) diff 10000 (95 ms)
[2019-08-29 19:30:34.739] speed 10s/60s/15m 228.3 n/a n/a H/s max 228.5 H/s
[2019-08-29 19:30:44.672] [CC-Client] Command: UPDATE_CONFIG received -> update config
[2019-08-29 19:30:45.087] [CC-Client] Config updated. -> reload
[2019-08-29 19:30:45.588] "/home/vidi/bin/xmrigCC/config.json" was changed, reloading configuration
 * POOL #1      iridium.herominers.com:10640 algo cn-pico
[2019-08-29 19:30:46.035] use pool iridium.herominers.com:10640  78.46.106.203
[2019-08-29 19:30:46.035] new job from iridium.herominers.com:10640 diff 50000 algo cn-pico
[2019-08-29 19:30:46.035]  cpu  use profile  cn-pico  (4 threads) scratchpad 256 KB
[2019-08-29 19:30:46.049]  cpu  READY threads 4(8) huge pages 4/4 100% memory 2048 KB (3 ms)
[2019-08-29 19:30:47.441] accepted (1622/0) diff 50000 (24 ms)
[2019-08-29 19:30:59.435] accepted (1623/0) diff 50000 (31 ms)
```

**Comment by Bendr0id** [comment] 2019-08-29 17:35
After the reload the miner appears for 20s with 0 hashrate but thats normal because the algo is changed and resetted...

**Comment by uz-spark** [comment] 2019-08-29 17:36
Actually for some reason when switching template backwards the original 'worker-id' field wasn't retained but was replaced with the one from template, that's because it's 'disappeared' from dashboard.

Unrelated issue, after i've switched VPNs worker on local machine doesn't resume mining. Config is the same as above. Log :

[2019-08-29 22:30:49.678] accepted (8/0) diff 200007 (83 ms)
[2019-08-29 22:30:49.948] [uplexa.herominers.com:10470] read error: "connection reset by peer"
[2019-08-29 22:30:49.950] no active pools, stop mining
[2019-08-29 22:31:19.885] speed 10s/60s/15m n/a n/a n/a H/s max 56566.5 H/s
[2019-08-29 22:32:20.177] speed 10s/60s/15m n/a n/a n/a H/s max 56566.5 H/s
[2019-08-29 22:33:20.582] speed 10s/60s/15m n/a n/a n/a H/s max 56566.5 H/s
[2019-08-29 22:34:20.987] speed 10s/60s/15m n/a n/a n/a H/s max 56566.5 H/s
[2019-08-29 22:35:21.404] speed 10s/60s/15m n/a n/a n/a H/s max 56566.5 H/s

**Comment by Bendr0id** [comment] 2019-08-29 17:37
Check your config:

```
  "retries": 5,
```

After that it won't retry anymore.

**Comment by Bendr0id** [comment] 2019-08-29 17:40
Actually it will, but it will take some time..

**Comment by uz-spark** [comment] 2019-08-29 17:40
Eh ? Why ? That's logical behavior if there's multiple pools so it'll switch between them but if there's only one why it would stop completely ? I'll try to replicate that with retries 999.

**Comment by Bendr0id** [comment] 2019-08-29 17:42
Thats xmrig behavior.. I didnt changed that. But i agree on xmrigcc 1.9.5 it  was infinit trying

**Comment by uz-spark** [comment] 2019-08-29 17:43
Hmm, okay. Please change it back, that's not right :)

**Comment by Bendr0id** [comment] 2019-08-29 17:46
Its not my fault... on XMRigCC < 2.0 i did all the network code on my own. 

I'm currently testing the behavior

**Comment by uz-spark** [comment] 2019-08-29 17:47
I'm not saying it's your fault, i'm just reporting it as a bug, it shouldn't behave like that.

**Comment by Bendr0id** [comment] 2019-08-29 17:52
But, see the log below. It works perfectly. I just didn't printout the tryouts anymore but it does keep trying.

```
* ABOUT        XMRigCC/2.0.0-beta gcc/8.3.0 (RELEASE)
 * LIBS         libuv/1.30.1 OpenSSL/1.1.1c hwloc/1.11.13
 * CPU          Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (1) x64 AES
                L2:1.0 MB L3:8.0 MB 4C/8T NUMA:1
 * DONATE       5%
 * ASSEMBLY     auto:intel
 * POOL #1      donate.graef.in:8888 algo auto
 * COMMANDS     hashrate, pause, resume
[2019-08-29 19:47:38.702] CC feature is disabled.
[2019-08-29 19:47:38.754] [donate.graef.in:8888] connect error: "connection refused"
[2019-08-29 19:47:44.748] [donate.graef.in:8888] connect error: "connection refused"
[2019-08-29 19:47:50.765] [donate.graef.in:8888] connect error: "connection refused"
[2019-08-29 19:47:56.777] [donate.graef.in:8888] connect error: "connection refused"
[2019-08-29 19:48:02.800] [donate.graef.in:8888] connect error: "connection refused"

no i turn the server on
[2019-08-29 19:49:44.536] speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s

[2019-08-29 19:49:56.951] use pool donate.graef.in:8888  3.123.78.48
[2019-08-29 19:49:56.951] new job from donate.graef.in:8888 diff 10000 algo cn/r height 1911577
[2019-08-29 19:49:56.951]  cpu  use profile  cn  (4 threads) scratchpad 2048 KB
[2019-08-29 19:49:57.463]  cpu  READY threads 4(4) huge pages 4/4 100% memory 8192 KB (512 ms)
[2019-08-29 19:50:00.461] SIGTERM received, exiting
[2019-08-29 19:50:00.515]  cpu  stopped (53 ms)
```

**Comment by Bendr0id** [comment] 2019-08-29 17:54
I can't see a problem. This is with the follow settings:

```
    "retries": 5,
    "retry-pause": 5,
```

I think otherwise ppl would have complain about that before.

**Comment by uz-spark** [comment] 2019-08-29 18:04
I just tried cycling Ethernet controller and unplugging+plugging Ethernet cable and starting miner without network and then enabling it. Behaviour is the same in all cases, with different errors. Neither "retries" nor "retry-pause" values affect it. The only difference between us seems to be OS (i assume you're on Linux).

**Comment by uz-spark** [comment] 2019-08-29 18:04
I'll try to replicate this on another machine.

**Comment by Bendr0id** [comment] 2019-08-29 18:05
Tried it on different variants of Linux and Windows 10 as well. Works for me in all cases, just needs some time to recover..

**Comment by uz-spark** [comment] 2019-08-29 18:14
It's the same on the other machine, different builds. Thought maybe it's pool dependent, nope, the same for me with your donate pool ...

**Comment by Bendr0id** [comment] 2019-08-29 18:17
Thats strange. 

Can you turn the this flag on and take some logs?

```
option(WITH_DEBUG_LOG       "Enable debug log output" ON)
```

You need to wipe the CMakeCache

**Comment by uz-spark** [comment] 2019-08-29 18:18
Also it doesn't start with your donate pool if i login field is longer than 45 symbols or pass field is longer than 21 symbols, what's going on here lol :D

**Comment by uz-spark** [comment] 2019-08-29 18:20
I use provided binaries, never compiled it, will try now.

**Comment by Bendr0id** [comment] 2019-08-29 18:23
https://github.com/xmrig/xmrig/issues/1138

There you go...

**Comment by Bendr0id** [comment] 2019-08-29 18:24
Similar one.. You're right when i "unplug" network of the vm and "plug" it again in it doesn't recover. Not very robust..

**Comment by Bendr0id** [comment] 2019-08-29 18:26
I'll look into it and if i find it i'll create a pull request to upstream.These guys did a great job with the last major rls. Appreciated.

**Comment by uz-spark** [comment] 2019-08-29 18:27
So it's upstream issue. I'll try to build with debug flag anyway.

**Comment by Bendr0id** [comment] 2019-08-29 18:30
There is no need. The issue already contains a debug log..

But whats with the first issue..? Is it working now?

**Comment by uz-spark** [comment] 2019-08-29 18:31
So, to recap all this, i had three separate-ish issues :
1) Miners stuck in 'invalid' algo state while still mining on previous algo, restart helps.
2) Sometimes applying template overwrites miner's 'worker-id' field.
3) Miners don't resume mining after loss of network (upstream issue).

**Comment by Bendr0id** [comment] 2019-08-29 18:34
Nr. 2 is a layer 8 problem. 
Either you checked merge-templates or just fu*** up something in the template.

**Comment by uz-spark** [comment] 2019-08-29 18:34
Checked merge-templates ?

**Comment by uz-spark** [comment] 2019-08-29 18:37
Also, it's independent of CC-server it seems. If i edit config locally it's the same behaviour (1)

**Comment by Bendr0id** [comment] 2019-08-29 18:39
Hmmmm did you use the api-worker field? If worker-id is specified, it uses the one from the api. If that is not available to it uses the host-name

**Comment by Bendr0id** [comment] 2019-08-29 18:40
can you please join the discord.. much easier to chat :D

**Comment by uz-spark** [comment] 2019-08-29 18:41
Uh ... yes. I replaced them two just in case :D

Server ?

**Comment by Bendr0id** [comment] 2019-08-29 18:41
https://discord.gg/XVrrEq

**Comment by Bendr0id** [comment] 2019-08-30 18:33
Any chance to check the new version?

**Comment by Bendr0id** [comment] 2019-08-30 18:43
fixed in evolved branch

**Closed by Bendr0id** 2019-08-30 18:43 UTC
