### ISSUE TITLE
[2.2.1] Please disable Rx* dev donate

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#287] opened 2019-12-12 08:16 UTC
It freezes my low-RAM miners :(

**Comment by uz-spark** [comment] 2019-12-12 08:19
Uplexa & Graft has still somewhat acceptable income and they work on anything. Or maybe you can implement RAM capacity check to fallback to less memory-hungry algo on low-end miners.

**Comment by uz-spark** [comment] 2019-12-12 08:22
Or add "low-ram-dev-donate" option.

**Comment by Bendr0id** [comment] 2019-12-12 08:34
First, the miner is detecting the low ram and turning into slow mode. 

But anyways if you completely want to disable rx donation for a miner, just disable the algo in the config with `"rx":false`.

The miner is announcing the capabilities to the donation proxy and based on that it assigns a job to to the miner.

Second option is you keccak your username, send it to me on telegram or discord and I'll whitelist your miners.

Best,
Ben

**Comment by uz-spark** [comment] 2019-12-12 08:41
>> just disable the algo in the config with "rx":false.
I didn't think of that, i'll do that, thanks.

>> First, the miner is detecting the low ram and turning into slow mode.
It's not like there's not enough RAM to allocate, there might be enough but it just sinks in all available RAM and OS becomes rather unresponsive. And i don't see any log entries for low ram mode, it just doesn't mine whatsoever, 0 H\s.

**Comment by Bendr0id** [comment] 2019-12-12 10:34
Does it work? Can we close this?

**Comment by uz-spark** [comment] 2019-12-12 10:36
It just doesn't mine but still tries to init it

[2019-12-12 15:31:41.426] dev donate started
[2019-12-12 15:31:41.427] new job from donate.graef.in:443 diff 200007 algo rx/0
[2019-12-12 15:31:41.427]  rx   init dataset algo rx/0 (4 threads) seed ed5d070fac5138ce...
[2019-12-12 15:31:41.427]  rx   #0 allocate 2336 MB (2080+256) for RandomX dataset & cache
[2019-12-12 15:31:41.485]  rx   #0 allocate done huge pages 0/1168 0% +JIT (58 ms)
[2019-12-12 15:31:50.864]  rx   #0 init done (9399 ms)
[2019-12-12 15:31:51.040] CPU disabled, no suitable configuration for algo rx/0
[2019-12-12 15:32:22.631] speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s
[2019-12-12 15:32:32.321] new job from donate.graef.in:443 diff 200007 algo rx/0
[2019-12-12 15:32:32.407] CPU disabled, no suitable configuration for algo rx/0
[2019-12-12 15:32:45.447] new job from uplexa.herominers.com:10470 diff 326688 algo cn-extremelite/upx2

**Comment by Bendr0id** [comment] 2019-12-12 10:38
Hmm did you restart the miner after changing the config? If not, please do and try again ..

**Comment by Bendr0id** [comment] 2019-12-12 10:39
It should not announce algos which have been disabled...

**Comment by uz-spark** [comment] 2019-12-12 10:40
Looks like i didn't, i'll report back in some time

**Comment by uz-spark** [comment] 2019-12-12 13:05
Nope, it doesn't work.

**Comment by uz-spark** [comment] 2019-12-12 14:17
Ok, i think i've pinned down the problem.
My miners disregard that "rx":false part when "autosave": false and there's not all algo configs were defined, as in there's only that entry and nothing else. Neither helps this "*": {"intensity": 1,"threads": 1,"affinity": -1} i don't know why that type of configuration even there when it doesn't work with autosave disabled and when enabled it just explodes it into all that wall of text. I've ended up enabling autosave, letting it to explode everything, disabling rx algo and disabling autosave again just in case, this way it works.

**Comment by Bendr0id** [comment] 2019-12-12 19:05
So what will work is this.

Keep autosave disabled as before. And add this to your config:
```
        "rx": false,
        "rx/arq": false,
        "rx/sfx": false,
        "rx/wow": false,
        "rx/loki": false,
```

Seems that there is a bug on my donation pool, even when rx/loki is sent it will send a rx/0 job because it seems not to parse the variant.

Could you please try this?

**Comment by uz-spark** [comment] 2019-12-12 19:16
It works but it's not about dev proxy, it's the config parsing in client. If i just put "rx": false with no other algo defined then it mines it if i configure it to do so, if i put all these algos in there as you said it doesn't mine, "incompatible algorithm".

**Comment by Bendr0id** [comment] 2019-12-12 19:33
Not thats not entirely correct.

When you just do `"rx":false` it will only disable rx/0 and rx. Any other RX algo like rx/loki, rx/wow etc will still be announces because they are note explicitly disabled.

So the miner is behaving correctly. My but my donation proxy is currently having a bug.

It just sees oh the is a miner announcing some ramdomx variant for example rx/wow, and then its assigning a rx/0 job to it because i dont have rx/wow configured.

When the rx algo is not found it needs to fallback to a cn based algo.

**Comment by Bendr0id** [comment] 2019-12-12 19:43
Please try this it will 100% work.

```
  "rx": false,
        "rx/arq": false,
        "rx/sfx": false,
        "rx/wow": false,
        "rx/loki": false,
```

**Comment by Bendr0id** [comment] 2019-12-12 19:50
You should get a cn/r job instead and it should not say incompatible algo. The issue is definitely on my end..

**Comment by uz-spark** [comment] 2019-12-14 10:08
Yep, it works :
[2019-12-14 14:58:31.968] dev donate started
[2019-12-14 14:58:31.969] new job from donate.graef.in:443 diff 10000 algo cn/r height 359212
[2019-12-14 14:58:31.969]  cpu  use profile  cn  (2 threads) scratchpad 2048 KB
[2019-12-14 14:58:33.019]  cpu  READY threads 2(2) huge pages 2/2 100% memory 4096 KB (1040 ms)
[2019-12-14 14:58:37.667] new job from donate.graef.in:443 diff 10000 algo cn/r height 359212
[2019-12-14 14:59:03.447] speed 10s/60s/15m 55.6 n/a n/a H/s max 59.3 H/s
[2019-12-14 14:59:31.967] dev donate finished
[2019-12-14 14:59:31.967] new job from uplexa.herominers.com:10470 diff 227283 algo cn-extremelite/upx2

**Closed** 2019-12-14 10:10 UTC

**Comment by Bendr0id** [comment] 2019-12-23 09:09
I modified my donation proxy. If possible could you please try with only ` "rx": false,`if it works?

**Comment by uz-spark** [comment] 2019-12-23 10:11
I doubt it would work neither it should behave this way because if you leave there just "rx": false, miner would mine Rx based algos if you configure so, it wouldn't if you put :false for Rx variants specifically. You need to modify config parsing logic to either make disabling base algo to disable all variants too or add smth like this "rx/*": false to disable all Rx based variants and base algo too, but "rx": false will disable just the base algo like it does now.

**Comment by Bendr0id** [comment] 2019-12-23 12:57
hmm. In my tests when i just put a "rx":false it disables rx at all.
