### ISSUE TITLE
unable to performRequest POST

### ISSUE THREAD

**Issue by escal3x** [Bendr0id/xmrigCC#279] opened 2019-11-09 00:40 UTC
I have problem:

`[CC-Client] error: unable to performRequest POST -> http://x.x.x.x/...url`

Client: Windows Server 2003 R2 SP2 (CCClient 2.1.0 version)
Server: Windows Server 2012 R2 (CCServer 2.1.0 version)

Similar questions have been asked here, but no answer has been given (as I understood, there was no way to reproduce the error). The problem occurs only on clients running Windows Server 2003 (x86). Clients running under Windows 8/8. 1/2012 / 2012R2/10 / 2016 do not report this error. Installing and updating Visual C components did not bring results.

After analyzing the source code, I came to the conclusion that the problem is related to the httplib library:

**CCClient.h**
```
    std::shared_ptr<httplib::Response> performRequest(const std::string &requestUrl,
                                                      const std::string &requestBuffer,
                                                      const std::string &operation);
```
**CCClient.cpp**
```
    auto res = performRequest(requestUrl, requestBuffer, "POST");
    if (!res) {
        LOG_ERR("[CC-Client] error: unable to performRequest POST -> http://%s:%d%s",
                m_base->config()->ccClient().host(), m_base->config()->ccClient().port(), requestUrl.c_str());
    } else if (res->status != 200) ...
```

How to fix? What are the solutions to this problem? My knowledge for this too little (in C/C++ little that understand). Maybe dear Bendr0id will be able to make appropriate amendments in the next releases?

**Comment by Bendr0id** [comment] 2019-11-12 20:24
I can't see a problem in that code. You just pasted some random code snippet here which doesn't have a problem or is related to that problem.

Does it happen with the official binaries?

Is it happening all the time or just sometimes?

May it be that the firewall blocks the requests? Are you using https?

**Comment by escal3x** [comment] 2019-11-17 00:00
Thx for reply, Bendr0id, but...
Official binaries were used. The problem only occurs with Windows 2003 servers. Problems with the POST request only occur after client version 2.0 (2.1-2.2). The http protocol is used. Using https help solve the problem?

**Comment by Bendr0id** [comment] 2019-11-17 07:55
In version 2.1 i upgraded the http lib to the latest version. Is it not working whole time on Windows 2003 or just sometimes?

**Comment by Bendr0id** [comment] 2019-11-22 21:23
I had a deeper look into this. 
I assume you're using TLS for the CC communication.

The problem i could imagine has todo with TLS verification. 

So for example if the server is located in .cn the TLS stream will be interrupted and modified by the goverment. In this case the newer client will fail..

**Comment by Bendr0id** [comment] 2019-12-12 10:34
Can you please try with version 2.2.1 if the problem still persists?

**Comment by escal3x** [comment] 2019-12-14 13:13
ok, will try this version and report the result soon

**Comment by ilya7zz** [comment] 2019-12-15 02:26
"[CC-Client] error: unable to performRequest POST -> /client/setClientConfig?clientId"
Today I updated several dozens of machines to 2.2.1 from older versions 1.9 *. The problem is observed in half of x86. Older versions contacted the server correctly. Lost 4 Win 7 clients.
Problems only with the processor Xeon(R) CPU E3-1230 V2 @ 3.30GHz

**Comment by Bendr0id** [comment] 2019-12-15 07:50
I have same CPU, it's not related to that. Are you using TLS?

**Comment by ilya7zz** [comment] 2019-12-15 12:30
TLS not use. Machines with the same cpu on a x64 works fine. Win 7 x86 - error.

**Comment by Bendr0id** [comment] 2019-12-15 16:45
Do you use my release or do you self compile?

**Comment by ilya7zz** [comment] 2019-12-15 17:19
I am using your release.

**Comment by Bendr0id** [comment] 2019-12-15 17:21
I'm currently setting up a Win7 x86 vm to reproduce.

**Comment by ilya7zz** [comment] 2019-12-15 17:24
If necessary, I will provide more information, if there are instructions :)

**Comment by Bendr0id** [comment] 2019-12-15 19:43
Hmm. Windows 7 32bit with SP1 works fine for me on the VM.

**Comment by ilya7zz** [comment] 2019-12-15 19:59
If I give access to Anydesk or TeamViewer, it will help to understand the situation?

**Comment by Bendr0id** [comment] 2019-12-15 20:18
can you send me a screenshot of the miner having the problem? IP's can be masked but the rest of the request i need.

**Comment by ilya7zz** [comment] 2019-12-16 05:04
![error-1](https://user-images.githubusercontent.com/53345402/70880610-a03e7200-1fda-11ea-8602-2e054ee98ec7.png)
![inf-1](https://user-images.githubusercontent.com/53345402/70880611-a03e7200-1fda-11ea-86a6-9d3d89a95a40.png)

**Comment by Bendr0id** [comment] 2019-12-16 13:46
[xmrigCC-2.2.1_debug_1.zip](https://github.com/Bendr0id/xmrigCC/files/3968281/xmrigCC-2.2.1_debug_1.zip)

Can you please try with this version? I did some changes and added more debug loigging. 

If possible please send me again a screenshort with that when the problem occurs.

**Comment by ilya7zz** [comment] 2019-12-17 00:12
![debug-1](https://user-images.githubusercontent.com/53345402/70953557-b56add80-207a-11ea-82e5-ce635f8821fc.png)

[debug-1.txt](https://github.com/Bendr0id/xmrigCC/files/3970757/debug-1.txt)

**Comment by Bendr0id** [comment] 2019-12-17 08:58
The log was very useful thx. I think i nailed it down to a windows call which is only supported on windows 7 sp1 and above.

Documentation says:
```
This flag is supported on Windows 7 with SP1, Windows Server 2008 R2 with SP1, and later
```

Could you please test if the attached file fixes it. If so i'll integrate it in the next release.

[xmrigCC_2.2.1_debug_2.zip](https://github.com/Bendr0id/xmrigCC/files/3972314/xmrigCC_2.2.1_debug_2.zip)

**Comment by ilya7zz** [comment] 2019-12-18 00:12
It works :)

**Closed** 2019-12-18 14:39 UTC
