### ISSUE TITLE
[2.5.0] Miner hangs on restart command

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#298] opened 2020-01-09 17:07 UTC
Miner hangs on restart command from CC server, both daemon and miner processes are still there but they're dead, neither mining nor connected to CC server.
Log:
[2020-01-09 22:04:23.509]  cc    Command: RESTART received -> trigger restart
[2020-01-09 22:04:23.513]  cpu  stopped (4 ms)

**Comment by Bendr0id** [comment] 2020-01-10 16:30
Is it recovering from that state or is it staying there forever?

**Comment by uz-spark** [comment] 2020-01-10 22:26
Didn't check, i'll see if it'll recover over the night.

**Comment by uz-spark** [comment] 2020-01-11 06:23
Nope, it doesn't recover.

**Comment by Bendr0id** [comment] 2020-01-14 08:19
i tried it several times on 10+ machines (linux) and wasn't able to reproduce yet. Is this happening on multiple machines?

**Comment by uz-spark** [comment] 2020-01-14 11:37
It happens on all my Windows machines, all Windows 10, various builds.

**Comment by uz-spark** [comment] 2020-01-15 12:25
Any luck with reproducing this ?

**Comment by MrCook1es** [comment] 2020-01-15 17:09
@Bendr0id 

I realized that I have the same problem too with 2.5.0 (I did some test with your precompiled bin)
both Windows7 and Windows10 are currently affected by this bug.
both "restart miner" and "stop miner" do not work!

the cursor continues to flash but nothing happens.
![immagine](https://user-images.githubusercontent.com/38523505/72454873-02e58200-37c2-11ea-8f6b-c3ffd76380f0.png)

**Comment by Bendr0id** [comment] 2020-01-19 08:00
![ArchLabs_2020-01-19-35_2560x1440](https://user-images.githubusercontent.com/383361/72677198-13d01500-3a9a-11ea-8c09-52864903a1e6.png)

I'm not able to reproduce this

**Comment by uz-spark** [comment] 2020-01-19 08:04
Hmm, maybe it's VM thing ? Believe me, it is 100% reproducible, i've bricked all my ~100 miners that day and still if i restart any of them now, they hangup until i manually restart the miner. Previous versions work just fine, 2.5.0 doesn't.

**Comment by Bendr0id** [comment] 2020-01-19 08:30
I believe, but still can't repro. It may be related to the resetting of the MSR registers.

Could you try again with this option:
`"rdmsr": false`

**Comment by uz-spark** [comment] 2020-01-19 08:35
Nope, still hangs up and drops off CC server. Well, and if it were related to reverting MSR registers it would hangup on manual exit too, it doesn't.

**Comment by Bendr0id** [comment] 2020-01-19 08:38
Thats not the whole truth. The restart command triggers the same which happens if you press 'q'. What do you mean by manual exit? Pressing 'q' or closing the Window? Closing the window is not the same.

**Comment by uz-spark** [comment] 2020-01-19 08:41
Hmm, i mean close the window, i assumed it does the same since it shouldn't just terminate on the place but receive close window signal and shutdown appropriately ...
It doesn't respond to 'q', pressing Ctrl-C quits without the problem tho.

**Comment by uz-spark** [comment] 2020-01-19 08:42
Pause & resume works too both from CC server and in miner console.

**Comment by uz-spark** [comment] 2020-01-19 08:44
I had to mention that it's not related to RandomX and MSR registers because it happens if i use other algos too.

**Comment by Bendr0id** [comment] 2020-01-19 08:47
Closing the window is not the same as pressing ctrl+c. I'm trying the walk through the code to find it. It's hard since i'm note able to reproduce

**Comment by uz-spark** [comment] 2020-01-19 09:03
I mean, there are no 'q' option on Windows versions of both XMRigCC and upstream XMRig so i'd assume that closing the window should trigger MSR reverting because it's literally the only way to shutdown the miner. But again, it happens on non Rx algos too so it's not about MSR.

**Comment by Bendr0id** [comment] 2020-01-19 09:52
Did you test the behavior on both, gcc and mvc build?

**Comment by uz-spark** [comment] 2020-01-19 10:08
Just tested, yes, it's the same both with GCC and MSVC builds.

**Comment by Bendr0id** [comment] 2020-01-19 10:57
Please try this branch: issue_298

**Comment by uz-spark** [comment] 2020-01-19 11:50
Gotta figure out how to build it first ...

**Comment by Bendr0id** [comment] 2020-01-19 22:33
Please give it a try now

**Comment by MrCook1es** [comment] 2020-01-20 08:55
> 
> 
> Please try this branch: issue_298

tested, same result as before:
-pause miner / start miner working
-stop miner / reboot miner not working

note: if I press "ctrl-c" or "Q" in this version "branch issue_298", they work.
if in the standard bin 2.5.0 I press "ctrl-c" it works. If I press "Q" nothing happens (no message)

**Comment by MrCook1es** [comment] 2020-01-20 09:11
@Bendr0id strange situation: if I use the 2.5.0 standard bin on a Windows VM, it works correctly.

**Closed** 2020-01-21 20:58 UTC
